<a href="https://colab.research.google.com/github/nikmahskb/python_for_datascience/blob/main/numpy_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# pip install numpy

In [ ]:
import numpy as np

## Soal 1

Buat contoh :

* numpy array (1D, 2D, 3D)
* numpy join
* numpy split
* operasi matrik

In [ ]:
## numpy array 1D
one_dim = np.array([56, 55, 54, 53, 52])

print(one_dim)

[56 55 54 53 52]


In [ ]:
## numpy array 2D
two_dim = np.array([[100, 110, 120, 130], [140, 150, 160, 170]])

print(two_dim)

[[100 110 120 130]
 [140 150 160 170]]


In [ ]:
## numpy array 3D
three_dim = np.array([[[11, 12, 13, 14], [14, 13, 12, 11]], [[1, 2, 3, 4], [4, 3, 2, 1]]])

print(three_dim)

[[[11 12 13 14]
  [14 13 12 11]]

 [[ 1  2  3  4]
  [ 4  3  2  1]]]


In [ ]:
## numpy join

exp1 = np.array([56, 55, 54, 53, 52])
exp2 = np.array([55, 56, 57, 58, 59])

arr1 = np.concatenate((exp1, exp2))
arr2 = np.stack((exp1, exp2))
arr3 = np.hstack((exp1, exp2))
arr4 = np.vstack((exp1, exp2))
arr5 = np.dstack((exp1, exp2))

print(f"numpy concatenate: \n {arr1} \n")

print(f"numpy stack: \n {arr2} \n")

print(f"numpy hstack: \n {arr3} \n")

print(f"numpy vstack: \n {arr4} \n")

print(f"numpy dstack: \n {arr5} \n")

numpy concatenate: 
 [56 55 54 53 52 55 56 57 58 59] 

numpy stack: 
 [[56 55 54 53 52]
 [55 56 57 58 59]] 

numpy hstack: 
 [56 55 54 53 52 55 56 57 58 59] 

numpy vstack: 
 [[56 55 54 53 52]
 [55 56 57 58 59]] 

numpy dstack: 
 [[[56 55]
  [55 56]
  [54 57]
  [53 58]
  [52 59]]] 



In [ ]:
## numpy split

# 1D
split_one = np.array([56, 55, 54, 53, 52, 55, 56, 57, 58, 59])
new_one = np.array_split(split_one, 5)

print(f"split 1D: \n {new_one} \n")

# 2D
split_two = np.array([[100, 110], [120, 130], [140, 150], [160, 170]])
new_two = np.array_split(split_two, 2)

print(f"split 2D: \n {new_two} \n")

# 3D
split_three = np.array([[70, 80, 90], [100, 110, 120], [130, 140, 150], [160, 170, 180], [190, 200, 210], [220, 230, 240]])
new_three = np.array_split(split_three, 3)

print(f"split 3D: \n {new_three} \n")

split 1D: 
 [array([56, 55]), array([54, 53]), array([52, 55]), array([56, 57]), array([58, 59])] 

split 2D: 
 [array([[100, 110],
       [120, 130]]), array([[140, 150],
       [160, 170]])] 

split 3D: 
 [array([[ 70,  80,  90],
       [100, 110, 120]]), array([[130, 140, 150],
       [160, 170, 180]]), array([[190, 200, 210],
       [220, 230, 240]])] 



In [ ]:
## Operasi matrik

matriks_a = np.array([
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]])

matriks_b = np.array([
            [16,15,14,13],
            [12,11,10,9],
            [8,7,6,5],
            [4,3,2,1]])


op_plus = matriks_a + matriks_b
print(f"Hasil penjumlahan: \n {op_plus} \n")

op_minus = matriks_a - matriks_b
print(f"Hasil pengurangan: \n {op_minus} \n")

op_power = np.power(matriks_a, 2)
print(f"Hasil perhitungan pangkat: \n {op_power} \n")

op_sin = np.sin(matriks_b)
print(f"Hasil sinus matriks: \n {op_sin} \n")

Hasil penjumlahan: 
 [[17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]
 [17 17 17 17]] 

Hasil pengurangan: 
 [[-15 -13 -11  -9]
 [ -7  -5  -3  -1]
 [  1   3   5   7]
 [  9  11  13  15]] 

Hasil perhitungan pangkat: 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]] 

Hasil sinus matriks: 
 [[-0.28790332  0.65028784  0.99060736  0.42016704]
 [-0.53657292 -0.99999021 -0.54402111  0.41211849]
 [ 0.98935825  0.6569866  -0.2794155  -0.95892427]
 [-0.7568025   0.14112001  0.90929743  0.84147098]] 



## Soal 2

* Buatlah numpy array dengan matrik ukuran 3x4 dan range array 10-30
* Kemudian lakukan flatten
* cari nilai statistik (mean, median, dsb)

In [ ]:
matriks1 = np.random.randint(10, 30, (3, 4))
print(matriks1)

[[10 11 12 10]
 [19 23 24 12]
 [20 15 28 19]]


In [ ]:
transform = matriks1.flatten()
print(transform)

[10 11 12 10 19 23 24 12 20 15 28 19]


In [ ]:
data1 = np.mean(transform)
data2 = np.median(transform)
data3 = np.max(transform)
data4 = np.min(transform)
data5 = np.std(transform)
data6 = np.var(transform)
data7 = np.percentile(transform, 25)
data8 = np.percentile(transform, 75)

print(f"{data1}, {data2}, {data3}, {data4}, {data5}, {data6}, {data7}, {data8}")

16.916666666666668, 17.0, 28, 10, 5.851756621353588, 34.243055555555564, 11.75, 20.75
